version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                user: pablo
                uid: 1000
        image: "laravel"
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
    db:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./.docker/db:/var/lib/mysql

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/

    admin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
